dev:
  xcworkspace: "/Users/felipets/Documents/Swat/TestLab/Projects/iOS/TestLab.xcworkspace"
  scheme: Testlab-cal
  configuration: Debug
  export_path: "releases/dev"

jenkins:
  xcworkspace: <%= ENV['WORKSPACE']%>/Project.xcworkspace
  scheme: TargetName
  configuration: Debug
  export_path: <%= ENV['WORKSPACE']%>/releases/normal
